extends: ["airbnb/base"]
parser: "babel-eslint"
env:
  es6: true
  node: true
  browser: true
  mocha: true
globals:
  firebase: true
settings:
  import/resolver:
    webpack:
      config: "webpack.config.babel.js"
